[package]
name = "k3-rust-example"
version = "0.1.0"
edition = "2021"

[dependencies]
k3-wasm-macros = { version = "0.1.5", features = ["nightly"] }
k3-wasm-sdk = "0.1.3"
uuid = { version = "1.5.0", features = ["v4"] }
